### ISSUE TITLE
Licensing terms?

### ISSUE THREAD

**Issue by glutanimate** [davidshepherd7/ankicli#6]
Hi there,

first of all thanks a lot for all the work you've put into `ankicli`. It has been instrumental in learning how to interact with anki-connect.

I was planning on using some of your code in a new project of mine and I was wondering which license I can assume.

Thanks a lot in advance.

-- Glutanimate

**Comment by davidshepherd7** [comment]
I'd probably go with AGPLv3 since that's what Anki is [using](https://github.com/dae/anki/blob/master/LICENSE), but if you want something less restrictive I'm open to suggestions :slightly_smiling_face:

**Comment by glutanimate** [comment]
AGPLv3 is perfect, thanks!
